### ISSUE TITLE
[BUG]: x & y axis labels are truncated and not visible on the dashboard

### ISSUE THREAD

**Issue by BirneyRJ** [RevealBi/Reveal.Sdk#401]
### SDK Version

1.6.7

### Client Framework

Angular

### Server Platform

None

### Operating System

Windows

### Description

I have a web client that runs reveal dashboards but for some reason the x & y axis labels are all truncated or aren't fitting on the screen.  Don't know if i have missed something in the set up or this is a bug but the dashboard works without truncated x & y axis labels when i run the dashboard through a desktop app.

Web Client

![Image](https://github.com/user-attachments/assets/ffb5ec18-29d0-40cc-958a-851fac69f9d3)

Desktop app (names have been covered on one of the graphs but everything is there

![Image](https://github.com/user-attachments/assets/cbec68c7-b6e6-4cd8-a400-674c30cd221d)

**Comment by TorreyBetts** [comment]
There has been a literal mountain of improvements and bug fixes for the charts since 1.6.7. Have you gave 1.7.4 a try to see if that fixes the issue?

**Comment by brianlagunas** [comment]
Yes, please update and try on the latest version. I believe this is no longer an issue. We actually have a bug submitted because we allow the labels to get too long #338

**Comment by BirneyRJ** [comment]
I updated to 1.7.4 but it hasn't made any difference.  Is there any way to forcibly resize a chart so it might show them properly.  I have already tried the updateSize method on the dashboard but that makes no difference.

**Comment by gkaveckis** [comment]
Hi @BirneyRJ, 
Some questions that comes to my mind... 
When you said Desktop.. is it a windows app ? or another angular local app?
Also you can check if the browser console is displaying any extra information when loading the dashboard and the labels are being cut.
It would be very helpful to have a small example reproducing it

Regards.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our release targeted for the beginning of July.

**Comment by Anonynym3845937** [comment]
1. In which version have you fixed the issue?
2. Can you describe the fix you made?

We tried multiple versions (up to 1.8.0) and none of them fix the issue.

Issue remains as mentioned in the few last comments.
